"""
AI PR review script — called from GitHub Actions.

Reads the PR diff from diff.txt, sends to Claude API,
posts the review as a PR comment via the GitHub API.

Environment variables required:
    ANTHROPIC_API_KEY
    GH_TOKEN
    GITHUB_REPOSITORY   (set automatically by GitHub Actions: owner/repo)
    PR_NUMBER           (set in the workflow from github.event.number)
"""

import json
import os
import sys

import httpx
from anthropic import Anthropic

# ── config ─────────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GH_TOKEN = os.environ["GH_TOKEN"]
GITHUB_REPOSITORY = os.environ["GITHUB_REPOSITORY"]
PR_NUMBER = os.environ["PR_NUMBER"]

client = Anthropic(api_key=ANTHROPIC_API_KEY)

# ── prompt ─────────────────────────────────────────────────────────────────────
REVIEW_PROMPT = """You are a senior DevOps engineer reviewing a pull request.
Review this diff and provide a structured code review focused on infrastructure quality and security.

Diff:
{diff}

---

Review the diff and respond in this exact markdown format:

## AI code review

### Summary
[1-2 sentences describing what this PR does]

### Security issues
[List any security issues found. If none, write "None found."]
- Each issue on its own line
- Include the file name and line reference where possible
- Rate each: 🔴 Critical | 🟠 High | 🟡 Medium | 🟢 Low

### Infrastructure concerns
[List any Terraform, Kubernetes, or CI/CD issues]
- Missing resource limits, overly permissive IAM, bad practices, etc.
- If none, write "None found."

### Missing error handling
[Places where failures are not handled gracefully]
- If none, write "None found."

### Hardcoded values
[Any hardcoded secrets, IPs, credentials, or environment-specific values]
- If none, write "None found."

### Suggestions
[Optional improvements — not blockers]
- Keep this to 3 items max

### Verdict
[APPROVE | REQUEST CHANGES | COMMENT]
Reason: [one sentence]

---

Rules:
- Only comment on what is in the diff — do not speculate about code not shown
- Be specific: reference file names and line numbers where possible
- If the diff is empty or only documentation changes, say so and approve
- Security issues and hardcoded secrets must always be flagged, never skipped
"""

# ── read diff ──────────────────────────────────────────────────────────────────
try:
    with open("diff.txt") as f:
        diff = f.read()
except FileNotFoundError:
    print("ERROR: diff.txt not found")
    sys.exit(1)

if not diff.strip():
    print("Diff is empty — nothing to review")
    sys.exit(0)

# Truncate very large diffs to avoid token limits
MAX_DIFF_CHARS = 15000
if len(diff) > MAX_DIFF_CHARS:
    diff = diff[:MAX_DIFF_CHARS] + "\n\n[diff truncated — too large for review]"
    print(f"Warning: diff truncated to {MAX_DIFF_CHARS} chars")

# ── call claude ────────────────────────────────────────────────────────────────
print("Sending diff to Claude for review...")

response = client.messages.create(
    model="claude-sonnet-4-5",
    max_tokens=2048,
    messages=[
        {
            "role": "user",
            "content": REVIEW_PROMPT.format(diff=diff),
        }
    ],
)

review_text = response.content[0].text
print("Review generated successfully")
print("---")
print(review_text)
print("---")

# ── post to github ─────────────────────────────────────────────────────────────
comment_body = f"{review_text}\n\n---\n*🤖 Generated by Claude AI — always review suggestions before acting on them*"

github_api_url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{PR_NUMBER}/comments"

response = httpx.post(
    github_api_url,
    headers={
        "Authorization": f"Bearer {GH_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    },
    json={"body": comment_body},
)

if response.status_code == 201:
    print(f"Review posted to PR #{PR_NUMBER}")
else:
    print(f"Failed to post review: {response.status_code} {response.text}")
    sys.exit(1)
